spring.application.name=projetinho

# Datasource para SQL Server
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=projetinho
spring.datasource.username=projetinho
spring.datasource.password=projetinho

# Mostrar SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true

# Dialeto do SQL Server
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# Atualização do esquema (use 'update' no lugar de 'create' em produção)
spring.jpa.hibernate.ddl-auto=update

