spring.application.name=projetinho

spring.datasource.url=jdbc:sqlserver://LUIS:1433;databaseName=projetinho;encrypt=true;trustServerCertificate=true
spring.datasource.username=projetinho
spring.datasource.password=projetinho
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
server.port=8087

# Mostrar SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialeto do SQL Server
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# Atualiza��o do banco automaticamente
spring.jpa.hibernate.ddl-auto=create
